[package]
name = "poly_embedder"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
rand = "0.8"
rustacuda = "0.1.3"
rustacuda_core = "0.1.2"
rustacuda_derive = "0.1.2"

[build-dependencies]
cc = "1.0"

[profile.release]
debug = true
